---
- hosts: pfservers
  name: upgrade OS to latest version
  become: True
  gather_facts: False
  tags: upgrade

  # to ensure nightly builds are always installed
  # on latest distribution versions when vagrant boxes take time
  # to be released
  tasks:
    - name: update to latest OS version
      package:
        name: '*'
        state: latest

- hosts: ['nightly', 'dev']
  name: install packetfence development packages
  become: True

  roles:
    - role: inverse_inc.gitlab_buildpkg_tools
      tags: ci

- hosts: pfservers
  name: install pf on standalone
  become: True
  collections:
    - inverse_inc.packetfence

  # search roles in collections
  roles:

    - role: packetfence_common
      tags: install

    - role: packetfence_install
      tags: install

  tasks:
    # We use another interface than the default as management
    # it's possible to do this because current SSH session has not been cut
    - name: allow ssh on default interface for vagrant management
      blockinfile:
        path: "{{ packetfence_install__conf_dir }}/iptables.conf"
        block: |
          # allow SSH for vagrant management
          -A INPUT --in-interface {{ ansible_default_ipv4['interface'] }} --jump ACCEPT
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: "-A INPUT --in-interface lo --jump ACCEPT"
      tags: vagrant
      register: site_register_iptables_rule

    - name: apply new iptables rule for vagrant management
      command: "{{ packetfence_install__pfcmd }} service iptables restart"
      when: site_register_iptables_rule is changed
      tags: vagrant

- hosts: dev
  name: configure environment for tests
  become: True
  collections:
    - debops.debops
    - inverse_inc.packetfence

  roles:
    # inject environment variables here to not conflict with install
    - role: environment
      tags: env

    - role: packetfence_go
      tags: go

- hosts: dev
  name: install additionnal stuff for dev machines
  become: True
  tags: build
  collections:
    - inverse_inc.packetfence

  roles:
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: "10.x"
      tags: nodejs
      
    - role: packetfence_dev
      tags: dev
