---
# Check if CI_COMMIT_TAG is defined (only when making a release) to disable devel repositories
# that contain install dependencies
release_status: '{{ True if lookup("env", "CI_COMMIT_TAG")
                         else False }}'

# set to package name to avoid installing packetfence-release
# from inverse.ca website (already installed based on pipeline
# artifacts)
packetfence_install__centos_release_rpm: 'packetfence-release'

packetfence_install__centos:
  repo: '{{ "packetfence" if release_status|bool
                          else "packetfence-devel" }}'

packetfence_install__deb:
  repos: '{{ ["debian"] if release_status|bool
                        else ["debian","debian-devel"] }}'


# config
# need to be defined here to be available to plays
# that not include packetfence_install role
packetfence_install__database_root_pass: secret

packetfence_install__fingerbank_setting:
  upstream:
    api_key: '{{ lookup("env", "FINGERBANK_API_KEY") }}'

